openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
servers:
  - url: /api
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/auth.yaml#/RegisterRequest'
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: './schemas/auth.yaml#/RegisterResponse'
        '400':
          description: Bad request
        500:
          description: Server error
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login and get token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/auth.yaml#/LoginRequest'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: './schemas/auth.yaml#/LoginResponse'
        '400':
          description: Bad request
        500:
          description: Server error
  /auth/logout:
    post:
      tags:
        - Auth
      summary: Logout User
      description: This method logout user
      responses:
        '200':
          description: User logout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyResource'
        '400':
          description: Bad request
        500:
          description: Server error
  /auth/current:
    get:
      tags:
        - Auth
      summary: Get current user by token
      description: Get current user by id
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: './schemas/auth.yaml#/RegisterResponse'
        '400':
          description: Bad request
        500:
          description: Server error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    PathId:
      in: path
      name: id
      required: true
      schema:
        type: integer
        minimum: 1
      description: Числовой id
      example: 1
    QueryInclude:
      in: query
      name: include
      required: false
      description: Relationships
      schema:
        type: string
  schemas:
    EmptyResource:
      type: object
      properties:
        data:
          type: object
          nullable: true
          example: null
