openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/auth.yaml#/RegisterRequest'
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: './schemas/auth.yaml#/RegisterResponse'
        '400':
          description: Bad request
        500:
          description: Server error
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login and get token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/auth.yaml#/LoginRequest'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: './schemas/auth.yaml#/LoginResponse'
        '400':
          description: Bad request
        500:
          description: Server error
  /auth/logout:
    post:
      tags:
        - Auth
      summary: Logout User
      description: This method logout user
      responses:
        '200':
          description: User logout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyResource'
        '400':
          description: Bad request
        500:
          description: Server error
  /users:
    get:
      tags:
        - Users
      summary: Get users list
      parameters:
        - name: filter
          in: query
          required: false
          schema:
            type: string
        - name: sort
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: './schemas/users.yaml#/UsersResponse'
        '401':
          description: Unauthorized
    post:
      tags:
        - Users
      summary: Create user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/users.yaml#/UserUpdateOrCreateRequest'
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: './schemas/users.yaml#/UserResponse'
        '400':
          description: Bad request
        500:
          description: Server error
  /users/{id}:
    get:
      tags:
        - Users
      summary: Get user by id
      description: Get user by id
      parameters:
        - $ref: '#/components/parameters/PathId'
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: './schemas/users.yaml#/UserResponse'
        '400':
          description: Bad request
        500:
          description: Server error
    delete:
      tags:
        - Users
      summary: Delete user by id
      description: Delete user by id
      parameters:
        - $ref: '#/components/parameters/PathId'
      responses:
        '200':
          description: User Deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyResource'
        '400':
          description: Bad request
        500:
          description: Server error
    patch:
      tags:
        - Users
      summary: Update user by id
      description: Update user by id
      parameters:
        - $ref: '#/components/parameters/PathId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schemas/users.yaml#/UserUpdateOrCreateRequest'
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: './schemas/users.yaml#/UserResponse'
        '400':
          description: Bad request
        500:
          description: Server error
  /users/current:
    get:
      tags:
        - Users
      summary: Get current by token
      description: Get current by id
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: './schemas/users.yaml#/UserResponse'
        '400':
          description: Bad request
        500:
          description: Server error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    PathId:
      in: path
      name: id
      required: true
      schema:
        type: integer
        minimum: 1
      description: Числовой id
      example: 1
    QueryInclude:
      in: query
      name: include
      required: false
      description: Relationships
      schema:
        type: string
  schemas:
    EmptyResource:
      type: object
      properties:
        data:
          type: object
          nullable: true
          example: null
